project:
  type: website
  # pre-render: 
  # - ???.R  # Download data?
  render:
  - index.qmd
  - sfer_mbon_stats.qmd  # render templated reports

website:
  title: "SFER+MBON Cruise Reports"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - sfer_mbon_stats.qmd
      - href: https://github.com/USF-IMaRS/mbon-sfer-cruise-data-inventory
        text: Source Code
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
    message: false
    warning: false


